# Generated by Django 4.2 on 2025-09-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subregistrar',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrars', to='myapp.subregistraroffice'),
        ),
    ]
