# Generated by Django 4.2 on 2025-09-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_subregistrar_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subregistrar',
            name='office',
        ),
        migrations.AddField(
            model_name='subregistrar',
            name='office_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
